language: crystal

install:
  - pushd ~ && git clone https://github.com/veelenga/ameba.git && cd ameba && make build && export PATH=$PATH:$PWD/bin && popd

script:
  - crystal spec
  - crystal tool format --check
  - ameba
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
